# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nadine_k/Documents/ZMQ/zeromq-lib61850

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nadine_k/Documents/ZMQ/zeromq-lib61850

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nadine_k/Documents/ZMQ/zeromq-lib61850/CMakeFiles /home/nadine_k/Documents/ZMQ/zeromq-lib61850//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nadine_k/Documents/ZMQ/zeromq-lib61850/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gateway

# Build rule for target.
gateway: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gateway
.PHONY : gateway

# fast build rule for target.
gateway/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateway.dir/build.make CMakeFiles/gateway.dir/build
.PHONY : gateway/fast

#=============================================================================
# Target rules for targets named client_sub

# Build rule for target.
client_sub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client_sub
.PHONY : client_sub

# fast build rule for target.
client_sub/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_sub.dir/build.make CMakeFiles/client_sub.dir/build
.PHONY : client_sub/fast

client_sub.o: client_sub.c.o
.PHONY : client_sub.o

# target to build an object file
client_sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_sub.dir/build.make CMakeFiles/client_sub.dir/client_sub.c.o
.PHONY : client_sub.c.o

client_sub.i: client_sub.c.i
.PHONY : client_sub.i

# target to preprocess a source file
client_sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_sub.dir/build.make CMakeFiles/client_sub.dir/client_sub.c.i
.PHONY : client_sub.c.i

client_sub.s: client_sub.c.s
.PHONY : client_sub.s

# target to generate assembly for a file
client_sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client_sub.dir/build.make CMakeFiles/client_sub.dir/client_sub.c.s
.PHONY : client_sub.c.s

gateway.o: gateway.c.o
.PHONY : gateway.o

# target to build an object file
gateway.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateway.dir/build.make CMakeFiles/gateway.dir/gateway.c.o
.PHONY : gateway.c.o

gateway.i: gateway.c.i
.PHONY : gateway.i

# target to preprocess a source file
gateway.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateway.dir/build.make CMakeFiles/gateway.dir/gateway.c.i
.PHONY : gateway.c.i

gateway.s: gateway.c.s
.PHONY : gateway.s

# target to generate assembly for a file
gateway.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gateway.dir/build.make CMakeFiles/gateway.dir/gateway.c.s
.PHONY : gateway.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client_sub"
	@echo "... gateway"
	@echo "... client_sub.o"
	@echo "... client_sub.i"
	@echo "... client_sub.s"
	@echo "... gateway.o"
	@echo "... gateway.i"
	@echo "... gateway.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

